HIT_Groups/Groups/urls.py
__author__ = 'jinyiyexing'

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.GroupsIndex, name='GroupsIndex'),
    url(r'^(?P<group_id>[0-9]+)/$',views.GroupDetail,name="GroupDetail"),
    url(r'^(?P<group_id>[0-9]+)/modify/$',views.GroupModify,name="GroupModify"),
    url(r'^create/$',views.GroupCreate,name="GroupCreate"),
    url(r'^(?P<group_id>[0-9]+)/delete/$',views.GroupDelete,name="GroupDelete"),
    url(r'^(?P<group_id>[0-9]+)/add/$',views.AddUser,name="GroupAdd"),
    url(r'^(?P<group_id>[0-9]+)/leave/$',views.EraseUser,name="GroupLeave"),
]

HIT_Groups/HIT_Groups/urls.py
from django.conf.urls import include, url, static
from django.contrib import admin
from django.contrib.auth import views
from Users import views as user_views
from Posts import views as post_views
from . import settings


urlpatterns = [
    url(r'^groups/', include('Groups.urls', namespace="Groups")),
    url(r'^users/', include('Users.urls', namespace="Users")),
    url(r'^posts/', include('Posts.urls', namespace='Posts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r"^$", user_views.root, name="root"),
    url(r"^login/$", views.login, {"template_name": "Users/login.html"}, name="login"),
    url(r"^logout/$", user_views.logout, name="logout"),
    url(r"^signup/$", user_views.signup, name="signup"),
    url(r'^messages/', include('django_messages.urls')),
    # url(r'^feedreader/', include('feedreader.urls', namespace='feedreader')),
    url(r"^changepassword/$", views.password_change, {"post_change_redirect": settings.LOGIN_URL}, name="change_password"),
    ]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HIT_Groups/Posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<post_id>[0-9]+)/modify/', views.post_update, name='post_update'),
    url(r'^$', views.post_create,name='post_create'),
    url(r'^(?P<post_id>[0-9]+)/delete/', views.post_delete, name='post_delete'),
    url(r'^(?P<post_id>[0-9]+)/', views.post_detail, name='post_detail'),
]

HIT_Groups/Groups/models.py
from django.db import models
from django.utils import timezone

class Group(models.Model):
    choices = (("发布消息", "发布消息"), ("兴趣爱好", "兴趣爱好"), ("社团信息", "社团信息"), ("消息推送", "消息推送"))
    name = models.CharField(max_length=200)
    create_time = models.DateTimeField('date created', default=timezone.now)
    update_time = models.DateTimeField('date updated', default=timezone.now)
    width = models.IntegerField(default=100)
    height = models.IntegerField(default=100)
    image = models.ImageField(upload_to='photos', height_field="height", width_field="width", default="avatar/hit.jpg")
    description = models.TextField()
    tag = models.CharField(max_length=10, choices=choices)
    permit = models.BooleanField()

    def __str__(self):
        return self.name

    def CanModifyGroups(self, user):
        if user.has_role_admin(self) or user.has_role_creator(self):
            return True
        else:
            return False

    def CanAddPosts(self, user):
        if user.has_role_user(self) and self.permit == False:
            return False
        else:
            return True

    def UserInGroup(self, user):
        user_list = self.myuser_set.all()
        if user in user_list:
            return True
        else:
            return False

    def GetPost(group):
        post_list = group.post_group.all()
        return post_list

    def GetLastPost(group):
        post_list = group.post_group.all().order_by("-posted_time")
        return post_list



HIT_Groups/Users/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import AbstractUser
from Groups.models import Group

# Create your models here.
class UsersAndGroups(models.Model):
    """
    Description: For many to many relationship and User Authority Description

    Todo:
        raw level authority
    """

    user_id = models.ForeignKey("MyUser")
    group_id = models.ForeignKey(Group)
    user_role = models.CharField(choices=
                                 (('Creator', 'Creator'),
                                  ("Admin", "Admin"),
                                  ("User", "User")), default="User", max_length = 20)

class MyUser(AbstractUser):
    """
    Description: User Description

    Todo:
        description
        tag
    """
    my_groups = models.ManyToManyField(Group, through = "UsersAndGroups")
    # password
    avatar = models.ImageField(upload_to='avatar/%Y/%m/%d', height_field="avatar_height", width_field="avatar_width", default="avatar/hit.jpg")
    avatar_height = models.IntegerField(default=100)
    avatar_width = models.IntegerField(default=100)

    def __str__(self):
        return self.username

    def has_role_creator(self, group):
        return True if \
            UsersAndGroups.objects.filter(user_id = self, group_id = group, user_role="Creator") \
            else False

    def has_role_admin(self, group):
        return True if \
            UsersAndGroups.objects.filter(user_id = self, group_id = group, user_role="Admin") \
            else False

    def has_role_user(self, group):
        return True if \
            UsersAndGroups.objects.filter(user_id = self, group_id = group, user_role="User") \
            else False

    def can_modify(self, obj):
        if obj.creator() == self:
            return True
        else:
            return False

    def creator(self):
        return self

    def get_group_by_id(self, id):
        return get_object_or_404(self.my_groups, id=id)

    def get_last_groups(self):
        return self.my_groups.order_by('-update_time')

HIT_Groups/Groups/forms.py
from django.forms import ModelForm

from .models import Group

class ContactForm(ModelForm):
    class Meta:
        model = Group
        fields = ('image', 'name', 'description', 'tag', 'permit')

HIT_Groups/Groups/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.utils import timezone
from .models import Group
from .forms import ContactForm
from Users.models import UsersAndGroups, MyUser


def GroupsIndex(request,format=None):
    group_list = Group.objects.order_by('-update_time')
    posts = []

    if group_list:
        cur_group = group_list[0]
        posts = cur_group.GetLastPost()
    else:
        cur_group = None
    if request.user.is_authenticated():
        if "group" in request.GET:
            cur_group = Group.objects.get(pk=(int(request.GET["group"])))
            posts = cur_group.GetLastPost()
    IsAdd = cur_group.UserInGroup(request.user)
    IsCreator = request.user.has_role_creator(cur_group)
    context = {'group_list': group_list, 'cur_group': cur_group, 'posts': posts,'IsAdd':IsAdd,'IsCreator':IsCreator}
    return render(request, 'Groups/Groupindex.html', context)


def GroupDetail(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    list = group.GetPost()
    return render(request, 'Groups/GroupDetail.html', {'group': group, "list": list})


def GroupModify(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if group.CanModifyGroups(request.user):
        if request.method == 'POST':
            form = ContactForm(request.POST, request.FILES)
            if form.is_valid():
                image = request.FILES["image"]
                name = form.cleaned_data["name"]
                description = form.cleaned_data["description"]
                tag = form.cleaned_data["tag"]
                permit = form.cleaned_data["permit"]
                group.image = image
                group.name = name
                group.description = description
                group.tag = tag
                group.permit = permit
                group.update_time = timezone.now()
                group.save()
                return HttpResponseRedirect('/groups/' + group_id + '/')
        else:
            form = ContactForm()
        return render(request, 'Groups/GroupModify.html', {'form': form, 'group': group})
    else:
        return HttpResponse("Sorry, you do not have the permission.")


def GroupCreate(request):
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            group = form.save()
            uag = UsersAndGroups.objects.create(user_id=request.user, group_id=group, user_role='Creator')
            uag.save()
            return HttpResponseRedirect('/groups/')
    else:
        form = ContactForm()
    return render(request, 'Groups/GroupCreate.html', {'form': form})


def GroupDelete(request, group_id):
    group = Group.objects.get(pk=group_id)
    if group.CanModifyGroups(request.user):
        group.delete()
        return render(request, 'Groups/GroupDelete.html')
    else:
        return HttpResponse("Sorry, you do not have the permission.")


def AddUser(request, group_id):
    group = Group.objects.get(pk=group_id)
    user_list = group.myuser_set.all()
    if request.user not in user_list:
        uag = UsersAndGroups.objects.create(user_id=request.user, group_id=group, user_role='User')
        uag.save()
        return HttpResponseRedirect('/groups/?group='+group_id)
    else:
        return HttpResponse("already in this group")

def EraseUser(request,group_id):
    group = Group.objects.get(pk=group_id)
    user = request.user
    uag = UsersAndGroups.objects.get(user_id=user,group_id=group)
    uag.delete()
    return HttpResponseRedirect('/groups/?group='+group_id)

HIT_Groups/Groups/templates/Groups/GroupCreate.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link href="{% static "css/updateform.css" %}" rel="stylesheet">
{% endblock headblock %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1 align="center">create a group</h1>

<form action="{% url 'Groups:GroupCreate'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-update">
        <div class="row">
                <div class="form-group-lg">
                    <label for="image">file</label>
                    <input type="file"  id="image" name="image" placeholder="{{form.name.value}}">
                </div>
                <div class="form-group-lg">
                    <label for="name">name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="{{form.name.value}}">
                </div>
                <div class="form-group-lg">
                    <label for="description">description</label>
                    <textarea class="form-control" id="description" name="description" rows="3" cols="10"
                              placeholder="{{form.description.value}}"></textarea>
                </div>
                <div class="form-group-lg">
                    <label for="tag">tag</label>
                    <select id="tag" name="tag" class="form-control" placeholder="{{form.tag.value}}">
                        <option value="" selected="selected">---------</option>
                        <option value="发布消息">发布消息</option>
                        <option value="兴趣爱好">兴趣爱好</option>
                        <option value="社团信息">社团信息</option>
                        <option value="消息推送">消息推送</option>
                    </select>
                </div>
                <div class="form-group-lg">
                    <label for="permit">permit</label>
                    <input type="checkbox" id="permit" name="permit"
                           placeholder="{{form.permit.value}}">
                </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>
{% endblock content %}

HIT_Groups/Groups/templates/Groups/GroupDelete.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
    <link href="{% static "css/groups.css" %}" rel="stylesheet">
{% endblock headblock %}
{% block content %}
<h1 align="center">删除成功!!</h1>
<footer>
    <p>
        <a align="center" href="{% url 'Groups:GroupsIndex' %}">返回圈子列表</a>
    </p>
</footer>
{% endblock content %}

HIT_Groups/Groups/templates/Groups/GroupDetail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link href="{% static "css/groups.css" %}" rel="stylesheet">
{% endblock headblock %}

{% block content %}
<div id="content" class="container-fluid main">
    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked">
                <li class="active">
                    <a href="#">all users</a>
                </li>
                {%for u in group.myuser_set.all %}
                <li><a href="/users/{{user.id}}">{{u.username}}</a></li>
                {% endfor %}
                <li class="active">
                    <a href="#">all posts</a>
                </li>
                {%for post in list%}
                    <li><a href="/groups/{{group.id}}/posts/{{post.id}}/comment">{{post.text}}</a></li>
                {%endfor%}
                <li><a href="{% url 'Posts:post_index' group.id %}">查看全部动态</a></li>
                <li><a href="{% url 'Posts:post_create' group.id %}">创建一个动态</a></li>
            </ul>
        </div>
        <div class="col-md-10">
            <div class="row">
                <div class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{group.name}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'Groups:GroupAdd' group.id %}">加入该圈子</a></li>
                        <li><a href="{% url 'Groups:GroupDelete' group.id %}">删除这个圈子</a></li>
                        <li><a href="{% url 'Groups:GroupModify' group.id %}">修改这个圈子</a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="post-list">
                    <img src="{{ group.image.url }}" width="100" height="300" class="avatar" />
                    <p>the create time is {{group.create_time}}</p>
                    <p>the latest update time is {{group.update_time}}</p>
                    <p>the group description is {{group.description}}</p>
                    <p>the group's tags are {{group.tag}}</p>
                    <p>the group allow users add comments ? {{group.permit}}</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}




HIT_Groups/Groups/templates/Groups/GroupIndex.html
{% extends "base.html" %}
{% load staticfiles %}
{% load usertag %}
{% block headblock %}
<link href="{% static " css/groups.css" %}" rel="stylesheet">
{% endblock headblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-info btn-sm btn btn-primary btn-lg btn-block">All Groups</button>
            <ul class="nav nav-pills nav-stacked">
                <li class="center-block"><a href="{% url 'Groups:GroupCreate' %}" class="center-block">create a group</a></li>
                {% if group_list %}
                {% for group in group_list %}
                <li class="{%if group.id == cur_group.id %} active {%endif%}"><a
                        href="{% url 'Groups:GroupsIndex' %}?group={{group.id}}">#{{group.name}}</a></li>
                {% endfor %}
                {% else %}
                <p>No groups are available</p>
                {% endif %}
        </div>
        <div class="col-md-6">
            <button type="button" class="btn btn-info btn-sm btn btn-primary btn-lg btn-block">the details of the group</button>
            <div class="row">
                <div class="col-md-6">
                    {% if cur_group %}
                    <img src="{{ cur_group.image.url }}" height="200" class="img-thumbnail" alt="Responsive image">
                    {% endif %}
                            {% if not IsAdd %}
                            <ul class="nav nav-pills nav-stacked">
                                <li class="center-block"><a href="{% url 'Groups:GroupAdd' cur_group.id %}"
                                                            class="center-block">join the group</a></li>
                            {% else %}
                                {% if not IsCreator %}
                                <ul class="nav nav-pills nav-stacked">
                                    <li class="center-block"><a href="{% url 'Groups:GroupLeave' cur_group.id %}"
                                                                class="center-block">leave the group</a></li>
                                    {% endif %}
                            {% endif %}
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <h3><span class="label label-success">{{cur_group.tag}}</span></h3>
                        </div>
                    </div>
                    <p class="text-primary">{{cur_group.description}}</p>
                    {% if cur_group.permit %}
                    <p class="text-success">this group allow user add posts!!</p>
                    {% else %}
                    <p class="text-warning">this group doesn't allow user add posts!!</p>
                    {% endif %}
                </div>
            </div>
            {% if IsCreator %}
            <div class="row">
                <div class="col-md-6">
                    <ul class="nav nav-pills nav-stacked">
                        <li class="center-block"><a href="{% url 'Groups:GroupDelete' cur_group.id %}"
                                                    class="center-block">delete the group</a></li>
                </div>
                <div class="col-md-6">
                    <ul class="nav nav-pills nav-stacked">
                        <li class="center-block"><a href="{% url 'Groups:GroupModify' cur_group.id %}"
                                                    class="center-block">modify the group</a></li>
                </div>
            </div>
            {% endif %}
            <!--<button type="button" class="btn btn-success btn-sm btn btn-primary btn-lg btn-block">圈子所有动态</button>-->
            {% if posts %}
            {% for post in posts %}
            <div class="row">
                <div class="col-md-2">
                    <img src="{{post.author.avatar.url}}" class="img-thumbnail" alt="Responsive image">
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-info">{{post.author.username}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-muted">{{post.posted_time.time}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 center-block">
                    <p class="bg-success center-block">{{post.text|markdownify|safe}}</p>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-info btn-sm btn btn-primary btn-lg btn-block">all users of the group</button>
            {%for u in cur_group.myuser_set.all %}
            <div class="row">
                <div class="col-md-4">
                    <img src="{{u.avatar.url}}" class="img-thumbnail" alt="Responsive image">
                </div>
                <div class="col-md-4">
                    <a href="/users/{{u.id}}">{{u.username}}</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}



HIT_Groups/Groups/templates/Groups/GroupModify.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link href="{% static "css/updateform.css" %}" rel="stylesheet">
{% endblock headblock %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1 align="center">Modify {{group.name}}</h1>

<form action="{% url 'Groups:GroupModify' group.id%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-update">
        <div class="row">
                <div class="form-group-lg">
                    <label for="image">file</label>
                    <input type="file" id="image" name="image" placeholder="{{form.name.value}}">
                </div>
                <div class="form-group-lg">
                    <label for="name">name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="{{form.name.value}}">
                </div>
                <div class="form-group-lg">
                    <label for="description">description</label>
                    <textarea class="form-control" id="description" name="description" rows="3" cols="10"
                              placeholder="{{form.description.value}}"></textarea>
                </div>
                <div class="form-group-lg">
                    <label for="tag">tag</label>
                    <select id="tag" name="tag" class="form-control" placeholder="{{form.tag.value}}">
                        <option value="" selected="selected">---------</option>
                        <option value="发布消息">发布消息</option>
                        <option value="兴趣爱好">兴趣爱好</option>
                        <option value="社团信息">社团信息</option>
                        <option value="消息推送">消息推送</option>
                    </select>
                </div>
                <div class="form-group-lg">
                    <label for="permit">permit</label>
                    <input type="checkbox" id="permit" name="permit"
                           placeholder="{{form.permit.value}}">
                </div>
        </div>
        <button type="submit" class="btn btn-primary">Modify</button>
    </div>
</form>
{% endblock content %}
