HIT_Groups/Groups/urls.py
__author__ = 'jinyiyexing'

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.GroupsIndex, name='GroupsIndex'),
    url(r'^(?P<group_id>[0-9]+)/$',views.GroupDetail,name="GroupDetail"),
    url(r'^(?P<group_id>[0-9]+)/modify/$',views.GroupModify,name="GroupModify"),
    url(r'^create/$',views.GroupCreate,name="GroupCreate"),
    url(r'^(?P<group_id>[0-9]+)/delete/$',views.GroupDelete,name="GroupDelete"),
    url(r'^(?P<group_id>[0-9]+)/add/$',views.AddUser,name="GroupAdd"),
    url(r'^(?P<group_id>[0-9]+)/leave/$',views.EraseUser,name="GroupLeave"),
]

HIT_Groups/HIT_Groups/urls.py
from django.conf.urls import include, url, static
from django.contrib import admin
from django.contrib.auth import views
from Users import views as user_views
from Posts import views as post_views
from . import settings


urlpatterns = [
    url(r'^groups/', include('Groups.urls', namespace="Groups")),
    url(r'^users/', include('Users.urls', namespace="Users")),
    url(r'^posts/', include('Posts.urls', namespace='Posts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r"^$", user_views.root, name="root"),
    url(r"^login/$", views.login, {"template_name": "Users/login.html"}, name="login"),
    url(r"^logout/$", user_views.logout, name="logout"),
    url(r"^signup/$", user_views.signup, name="signup"),
    url(r'^messages/', include('django_messages.urls')),
    # url(r'^feedreader/', include('feedreader.urls', namespace='feedreader')),
    url(r"^changepassword/$", views.password_change, {"post_change_redirect": settings.LOGIN_URL}, name="change_password"),
    ]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HIT_Groups/Posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<post_id>[0-9]+)/modify/', views.post_update, name='post_update'),
    url(r'^$', views.post_create,name='post_create'),
    url(r'^(?P<post_id>[0-9]+)/delete/', views.post_delete, name='post_delete'),
    url(r'^(?P<post_id>[0-9]+)/', views.post_detail, name='post_detail'),
]

HIT_Groups/Users/urls.py
from django.conf.urls import url

from .views import UserUpdate

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)$', UserUpdate.as_view(), name="UserUpdate"),
]

HIT_Groups/Users/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import AbstractUser
from Groups.models import Group

# Create your models here.
class UsersAndGroups(models.Model):
    """
    Description: For many to many relationship and User Authority Description

    Todo:
        raw level authority
    """

    user_id = models.ForeignKey("MyUser")
    group_id = models.ForeignKey(Group)
    user_role = models.CharField(choices=
                                 (('Creator', 'Creator'),
                                  ("Admin", "Admin"),
                                  ("User", "User")), default="User", max_length = 20)

class MyUser(AbstractUser):
    """
    Description: User Description

    Todo:
        description
        tag
    """
    my_groups = models.ManyToManyField(Group, through = "UsersAndGroups")
    # password
    avatar = models.ImageField(upload_to='avatar/%Y/%m/%d', height_field="avatar_height", width_field="avatar_width", default="avatar/hit.jpg")
    avatar_height = models.IntegerField(default=100)
    avatar_width = models.IntegerField(default=100)

    def __str__(self):
        return self.username

    def has_role_creator(self, group):
        return True if \
            UsersAndGroups.objects.filter(user_id = self, group_id = group, user_role="Creator") \
            else False

    def has_role_admin(self, group):
        return True if \
            UsersAndGroups.objects.filter(user_id = self, group_id = group, user_role="Admin") \
            else False

    def has_role_user(self, group):
        return True if \
            UsersAndGroups.objects.filter(user_id = self, group_id = group, user_role="User") \
            else False

    def can_modify(self, obj):
        if obj.creator() == self:
            return True
        else:
            return False

    def creator(self):
        return self

    def get_group_by_id(self, id):
        return get_object_or_404(self.my_groups, id=id)

    def get_last_groups(self):
        return self.my_groups.order_by('-update_time')

HIT_Groups/Posts/forms.py
from .models import Post, Comment
from django import forms
from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
    text = forms.CharField(widget=PagedownWidget())
    class Meta:
        model = Post
        fields = ("text", )

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=PagedownWidget())
    class Meta:
        model = Comment
        fields = ("text", )

HIT_Groups/Users/forms.py
from .models import MyUser
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _


class MyUserForm(forms.ModelForm):
    """MyUserForm for signup and singin"""
    class Meta:
        model = MyUser
        fields = ["username", "email"]


# just add email field for django UserCreationForm
class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = MyUser
        fields = ("username", "email")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

HIT_Groups/Users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.core import exceptions
from Users.models import MyUser
from Users.forms import MyUserForm, UserCreationForm
from HIT_Groups.settings import LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL, PAGENUM
from util import can_trans, page


def root(request, format=None):
    posts = []
    cur_group = None
    CAN_POST = True
    groups = []
    if request.user.is_authenticated():
        groups = request.user.get_last_groups()
        if "group" in request.GET:
            cur_group = request.user.get_group_by_id(
                can_trans(int, request.GET["group"]))
            posts.extend(cur_group.GetLastPost())
            CAN_POST = cur_group.CanAddPosts(request.user)
        else:
            for p in groups:
                posts.extend(p.GetLastPost())
    return render(request, "Users/index.html", {"groups": groups, "cur_group": cur_group, "posts": page(request, posts), "CAN_POST": CAN_POST})


def logout(request):
    django_logout(request)
    return HttpResponseRedirect(LOGOUT_REDIRECT_URL)


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(LOGIN_REDIRECT_URL)
    else:
        form = UserCreationForm()
    return render(request, 'Users/signup.html', {'form': form})


class UserUpdate(UpdateView):
    model = MyUser
    fields = ['username', 'avatar', "email"]
    success_url = LOGIN_REDIRECT_URL
    template_name = "Users/user_update.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user.can_modify(self.object):
            return super().post(request, *args, **kwargs)
        else:
            return HttpResponseForbidden("Sorry, you do not have the permission.")

HIT_Groups/Users/templates/Users/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load usertag %}
{% block headblock %}
{% endblock headblock %}
{% block content %}
<div id="content" class="container-fluid main">
    <div class="row">
        <div class="col-md-2 nav-groups">
            <ul class="nav nav-pills nav-stacked">
                <li>
                    <a href="{% url 'root' %}" >All Posts</a>
                </li>
                {% if not groups %}
                <h4>No groups,go to <a href="{% url 'Groups:GroupsIndex' %}">add groups</a></h4>
                {% endif %}
                {% for group in groups %}
                <li class="{%if group.id == cur_group.id %} active {%endif%}"><a href="{% url 'root' %}?group={{group.id}}"># {{group.name}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-10 post-container">
            {% if cur_group %}
            <div class="row">
                <div class="dropdown group-dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{cur_group.name}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'Groups:GroupsIndex' %}?group={{cur_group.id}}">Preference</a></li>
                        <li><a href="{% url 'Groups:GroupModify' cur_group.id %}">Modify</a></li>
                        <li><a href="{% url 'Groups:GroupLeave' cur_group.id %}">Leave</a></li>
                    </ul>
                </div>
            </div>
            {% if cur_group.id != None and CAN_POST%}
            <div class="row">
                <form action="{% url 'Posts:post_create'%}?group={{cur_group.id}}" method="post">
                    {% csrf_token %}
                    <div class="inline-post">
                        <label for="id_text" class="sr-only"></label>
                        <textarea name="text" id="id_text" class="form-control" rows="2" placeholder="you can use markdown"></textarea>
                        <div>
                            <button type="submit" class="btn btn-primary">New Post</button>
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
            {% endif %}
            <div class="row">
                <div class="post-list">
                    {% if not posts %}
                    <h4>No posts</h4>
                    {% endif %}
                    {% for post in posts %}
                    {# <hr> #}
                    <div class="row">
                        <div class="col-md-1 post-avatar">
                            <img src="{{ post.author.avatar.url }}" class="avatar" />
                        </div>
                        <div class="col-md-11 post-content">
                            <div class="row">
                                <div class="col-md-11 post-meta">
                                    <p class="post-meta"><a href="{% url 'Users:UserUpdate' post.author.id%}">{{post.author.username}}</a></p>
                                    <p class="post-meta">{{post.posted_time}}</p>
                                </div>
                                <div class="dropdown group-dropdown" style="float: right">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">more<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url 'Posts:post_detail' post.id %}">Comment</a></li>
                                        {% ifequal user post.author %}
                                        <li><a href="{% url 'Posts:post_update' post.id %}">Modify</a></li>
                                        <li><a href="{% url 'Posts:post_delete' post.id %}?group={{cur_group.id}}">Delete</a></li>
                                        {% endifequal %}
                                    </ul>
                                </div>
                            </div>
                            <div class="row">
                                <div class="post">
                                    {{post.text|markdownify|safe}}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="pagination">
                <span class="step-links">
                {% if posts.has_previous %}
                {% if cur_group %}
                <a href="{{request.get_path}}?group={{cur_group.id}}&page={{ posts.previous_page_number }}">previous</a>
                {% else %}
                <a href="{{request.get_path}}?page={{ posts.previous_page_number }}">previous</a>
                {% endif %}
                {% endif %}
                <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                </span>
                {% if posts.has_next %}
                {% if cur_group %}
                <a href="{{request.get_path}}?group={{cur_group.id}}&page={{ posts.next_page_number }}">next</a>
                {% else %}
                <a href="{{request.get_path}}?page={{ posts.next_page_number }}">next</a>
                {% endif %}
                {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

HIT_Groups/Users/templates/Users/login.html
{% load staticfiles %}
{% load i18n %}
{% load usertag %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">
    <title>Login for HIT Groups</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/groups.css" %}" rel="stylesheet">
    <link href="{% static "css/updateform.css" %}" rel="stylesheet">
</head>

<body>
    <div class="container">
        {% block form %}
        {% if next %}
        <form class="form-update" action="{% url 'login' %}?next={{next}}" method="POST">
        {%else%}
        <form class="form-update" action="{% url 'login' %}" method="POST">
        {% endif %}
            {% csrf_token %}
            <h2 class="text-center">HIT Groups</h2>
            {% include "form_errors.html" %}
            <div class="form-group-lg">
                {{ form.username.errors }}
                {{ form.username.label_tag }}
                {{ form.username|add_attributes:'form-control,required:'}}
            </div>
            <div class="form-group-lg">
                {{ form.password.errors }}
                {{ form.password.label_tag }}
                {{ form.password|add_attributes:'form-control,required:'}}
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            <h4 class="text-center">or <a href="{% url 'signup' %}">Sign up</a></h4>
        </form>
        {% endblock form %}
    </div>
</body>

</html>

HIT_Groups/Users/templates/Users/myuser_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load usertag %}
{% block headblock %}
<link href="{% static "css/updateform.css" %}" rel="stylesheet">
{% endblock headblock %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-update">
        {% if form.errors and not form.non_field_errors %}
        <p class="errornote">
        {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </p>
        {% endif %}

        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="errornote">
            {{ error }}
        </p>
        {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-md-8">
                <div class="form-group-lg">
                {{ form.username.errors }}
                {{ form.username.label_tag }}
                {{ form.username|add_attributes:'form-control,required:'}}
                </div>
                <div class="form-group-lg">
                {{ form.email.errors }}
                {{ form.email.label_tag }}
                {{ form.email|add_attributes:'form-control,required:'}}
                </div>
            </div>
            <div class="col-md-4">
                    <p><img src="{{ form.instance.avatar.url }}" width="100" height="100" class="avatar"/></p>
                <div class="form-group-lg">
                    <label for="avatar" class="sr-only"></label>
                    <input type="file" id="avatar" name="avatar">
                </div>
            </div>
        </div>
        {% if request.path|is_current_user_profile:user %}
        <button type="submit" class="btn btn-primary">Update</button>
        <div class="text-center">
        <a href="{%url 'change_password' %}" class="btn btn-primary">Change Password</a>
        </div>
        {% else %}
        <div class="profile-button text-center">
        <a href="{%url 'messages_compose_to' form.username.value%}" class="btn btn-primary">Send Message</a>
        </div>
        {% endif %}
    </div>
</form>
{% endblock content %}

HIT_Groups/Users/templates/Users/signup.html
{% extends "Users/login.html" %}
{% load staticfiles %}
{% load usertag %}
{% load i18n %}
{% block form %}
 <form class="form-update" action="{% url 'signup' %}" method="POST">
    {% csrf_token %}
    <h2 class="text-center">HIT Groups</h2>
    {% include "form_errors.html" %}
    <div class="form-group-lg">
    {{ form.username.errors }}
    {{ form.username.label_tag }}
    {{ form.username|add_attributes:'form-control,required:'}}
    </div>
    <div class="form-group-lg">
    {{ form.email.errors }}
    {{ form.email.label_tag }}
    {{ form.email|add_attributes:'form-control,required:'}}
    </div>
    <div class="form-group-lg">
    {{ form.password1.errors }}
    {{ form.password1.label_tag }}
    {{ form.password1|add_attributes:'form-control,required:'}}
    </div>
    <div class="form-group-lg">
    {{ form.password2.errors }}
    {{ form.password2.label_tag }}
    {{ form.password2|add_attributes:'form-control,required:'}}
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
  </form>
{% endblock form %}

HIT_Groups/Users/templates/Users/user_update.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load usertag %}
{% block headblock %}
<link href="{% static "css/updateform.css" %}" rel="stylesheet">
{% endblock headblock %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-update">
        {% include "form_errors.html" %}
        <div class="row">
            <div class="col-md-8">
                <div class="form-group-lg">
                {{ form.username.errors }}
                {{ form.username.label_tag }}
                {{ form.username|add_attributes:'form-control,required:'}}
                </div>
                <div class="form-group-lg">
                {{ form.email.errors }}
                {{ form.email.label_tag }}
                {{ form.email|add_attributes:'form-control,required:'}}
                </div>
            </div>
            <div class="col-md-4">
                    <p><img src="{{ form.instance.avatar.url }}" width="100" height="100" class="avatar"/></p>
                <div class="form-group-lg">
                    <label for="avatar" class="sr-only"></label>
                    <input type="file" id="avatar" name="avatar">
                </div>
            </div>
        </div>
        {# may it can be handle in view, but it is too complication #}
        {% if request.path|is_current_user_profile:user %}
        <button type="submit" class="btn btn-primary">Update</button>
        <div class="text-center">
        <a href="{%url 'change_password' %}" class="btn btn-primary">Change Password</a>
        </div>
        {% else %}
        <div class="profile-button text-center">
        <a href="{%url 'messages_compose_to' form.username.value%}" class="btn btn-primary">Send Message</a>
        </div>
        {% endif %}
    </div>
</form>
{% endblock content %}